<?php
include('Templates/header.php');
include('Templates/nav.php');
include('Templates/carousel.php');
include('Templates/produtos.php');
include('Templates/sobre.php');
include('Templates/contato.php');
include('Templates/footer.php');
include('Templates/end.php');
